"""Remove unique constraint from name field in users table

Revision ID: 33078c3dcf04
Revises: 4c9edeb0e762
Create Date: 2024-11-06 19:12:02.693851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33078c3dcf04'
down_revision = '4c9edeb0e762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_name')
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.create_index('ix_users_name', ['name'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
