"""Add last_login and created_at to User model

Revision ID: 72935a90bb77
Revises: d0dc87d046aa
Create Date: 2024-11-18 14:16:18.071108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72935a90bb77'
down_revision = 'd0dc87d046aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
